const html = `<!DOCTYPE html>
<body>
  <h1>__TITLE__</h1>
  <p>This markup was generated by a JS WASM Worker.</p>
</body>`;

export const handleRequest = async function (request) {
    const title = await request.text();

    return new Response(html.replace('__TITLE__', title), {
        status: 200,
        headers: {
            "content-type": "text/html;charset=UTF-8",
        },
    });
};
