const html = `<!DOCTYPE html>
<body>
  <h1>Hello World</h1>
  <p>This markup was generated by a JS WASM Worker.</p>
</body>`;

export const handleRequest = function (request) {
    return new Response(html, {
        status: 200,
        headers: {
            "content-type": "text/html;charset=UTF-8",
        },
    });
};
